name: liquibase
run-name: Setting up the Liquibase database
on:
    pull_request:
        types: [closed]

jobs:
  test-output:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: liquibase-github-actions/update@v4.26.0
          with:
            # The root changelog
            # string
            # Required
            changelogFile: "change/changelog.sql"
        
            # The JDBC database connection URL
            # string
            # Required
            url: ${{ secrets.URL }}
        
            # Password to use to connect to the database
            # string
            # Optional
            password: ${{ secrets.PASSWORD }}
        
            # Username to use to connect to the database
            # string
            # Optional
            username: ${{ secrets.USERNAME }}