name: liquibase
run-name: Setting up the Liquibase database
on:
    pull_request:
        types: [closed]

jobs:
  test-output:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: liquibase/liquibase-github-action@v7
        with:
          operation: 'update'
          classpath: 'example/changelogs'
          changeLogFile: 'changelog.sql'
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          url: ${{ secrets.URL }}
